export const featuredPhonesMock = [
    {
        id: "15910",
        name: "iPhone 8",
        imageURL: "https://img1.doctorsim.com/img/term/iphone_6.png",
        desc: "The iPhone 6 is Apple’s sixth generation Smartphone succeeding the iPhone 5S. Launched in September 2014, along with the larger-sized iPhone 6 Plus, the iPhone 6 quickly became a huge hit among Apple enthusiasts. With its new Retina HD 4.7-inch screen, the iPhone 6 is larger than previous generations. Other features include a faster A8 64-bit processor, an upgraded camera and support for the new Apple Pay mobile payments service. But the best thing about the iPhone 6 is that you can unlock it fast and safe, with the quality you would expect with a phone of this magnitude. At <strong>doctorSIM</strong>, the price will be unbeatable, you will receive expert customer support throughout the service and the speed at which we unlock your iPhone will be as fast as its processor! The phone manufacturer’s warranty will remain intact and the iPhone never has to leave your side. Your iPhone 6 will be unlocked via e-mail and iTunes. Unlocking your iPhone 6 with doctorSIM is <strong>100% legal</strong>, <strong>permanent</strong> and will not damage the iPhone in any way. We offer a full guarantee and will issue a full refund if for any reason under our responsibility are unable to unlock your iPhone.",
    },
    {
        id: "15911",
        name: "iPhone X",
        imageURL: "https://img1.doctorsim.com/img/term/iphone_x.png",
        description: "The iPhone 6 is Apple’s sixth generation Smartphone succeeding the iPhone 5S. Launched in September 2014, along with the larger-sized iPhone 6 Plus, the iPhone 6 quickly became a huge hit among Apple enthusiasts. With its new Retina HD 4.7-inch screen, the iPhone 6 is larger than previous generations. Other features include a faster A8 64-bit processor, an upgraded camera and support for the new Apple Pay mobile payments service. But the best thing about the iPhone 6 is that you can unlock it fast and safe, with the quality you would expect with a phone of this magnitude. At <strong>doctorSIM</strong>, the price will be unbeatable, you will receive expert customer support throughout the service and the speed at which we unlock your iPhone will be as fast as its processor! The phone manufacturer’s warranty will remain intact and the iPhone never has to leave your side. Your iPhone 6 will be unlocked via e-mail and iTunes. Unlocking your iPhone 6 with doctorSIM is <strong>100% legal</strong>, <strong>permanent</strong> and will not damage the iPhone in any way. We offer a full guarantee and will issue a full refund if for any reason under our responsibility are unable to unlock your iPhone.",
    },
    {
        id: "15912",
        name: "iPhone Xs",
        imageURL: "https://img1.doctorsim.com/img/term/iphone_xs.png",
        description: "The iPhone 6 is Apple’s sixth generation Smartphone succeeding the iPhone 5S. Launched in September 2014, along with the larger-sized iPhone 6 Plus, the iPhone 6 quickly became a huge hit among Apple enthusiasts. With its new Retina HD 4.7-inch screen, the iPhone 6 is larger than previous generations. Other features include a faster A8 64-bit processor, an upgraded camera and support for the new Apple Pay mobile payments service. But the best thing about the iPhone 6 is that you can unlock it fast and safe, with the quality you would expect with a phone of this magnitude. At <strong>doctorSIM</strong>, the price will be unbeatable, you will receive expert customer support throughout the service and the speed at which we unlock your iPhone will be as fast as its processor! The phone manufacturer’s warranty will remain intact and the iPhone never has to leave your side. Your iPhone 6 will be unlocked via e-mail and iTunes. Unlocking your iPhone 6 with doctorSIM is <strong>100% legal</strong>, <strong>permanent</strong> and will not damage the iPhone in any way. We offer a full guarantee and will issue a full refund if for any reason under our responsibility are unable to unlock your iPhone.",
    }

]